# British Crown Copyright 2026, Met Office. Please see LICENSE.md for license details.
site_name: CDDS CMIP7 Simulation Metadata
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
    - content.tabs.link
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: light green
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home:
    - About: index.md
    - What Is CMIP7?:  what_is_cmip7.md
  - Simulation Metadata Explained: simulation_metadata_explained.md
  - Registered Simulations:
    - The Registration Process: registering_a_simulation.md
    - Table Of Registered Simulations: metadata_tables/index.html
  - Variable Status:
    - Baseline Climate Variables: bcvs.md 
    - BCV Status Table: bcvs_table.html
  - ESGF Datasets:
    - What is ESGF?: a.md
    - Data: a.md # Link to ESGF datasets
    - Errata: a.md # Link to relevant errata records
  - CMIP7 Models:
    - UKCM2-0-LL: models/ukcm2.md
    - UKCM2a-0-HH: models/ukcm2a.md
    - UKESM1-3-LL: models/ukesm1-3.md
  - CMIP7 MIPs:
    - AerChemMIP: mips/aerchemmip.md
    - C4MIP: mips/c4mip.md
    - CFMIP: mips/cfmip.md
    - CMIP: mips/cmip.md
    - DAMIP: mips/damip.md
    - DCPP: mips/dcpp.md
    - GeoMIP: mips/geomip.md
    - LMIP: mips/lmip.md
    - PMIP: mips/pmip.md
    - PolMIP: mips/polmip.md
    - RFMIP: mips/rfmip.md
    - ScenarioMIP: mips/scenariomip.md
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji
  - pymdownx.details
  # - pymdownx.snippets:
  #     auto_append:
  #       - includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true
extra:
  version:
    provider: mike
plugins:
- search  
# - gen-files:
#     scripts:
#     - scripts/changes.py
#     - scripts/mappings.py
# - literate-nav:
#     nav_file: SUMMARY.md
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: sphinx
- section-index