# (C) British Crown Copyright 2026, Met Office.
# Please see LICENSE.md for license details.

# NOTE: This issue template is the required to feed the relavent information to '.github/workflows/generate_request.yml'
# and 'scripts/generate_request.py'. Changes to this template may result in errors.

name: "Request The Generation Of A CDDS Request File"
description: Request The Generation Of A CDDS Request File. Please note, i order to generate a request file, workflow metadata form must have been completed and submitted for the appropriate model workflow ID.
title: "Request The Generation Of A CDDS Request File: <insert model workflow id here>"
labels: ['request_file_request']
body:

  - type: markdown
    attributes:
      value: |
        # Request the generation of a CDDS request file...

  - type: input
    id: model_workflow_id
    attributes:
      label: Model Workflow ID
      description: Please provide the model workflow ID that you wish to generate a request file for.
      placeholder: "u-dv623"
    validations:
      required: true

  - type: dropdown
    id: request_type
    attributes:
      label: Request Type
      description: The type of request to generate. Unless using JASMIN, please select the default "Standard Met Office Request".
      options:
        - Standard Met Office Request
        - JASMIN Request
      default: 0
    validations:
      required: true

  - type: dropdown
    id: streams
    attributes:
      label: Streams
      description: The stream(s) you wish to process with.
      multiple: true
      options:
        - ap4
        - ap5
        - ap6
        - ap7
        - ap8
        - ap9
        - apu
        - apt
        - inm
        - onm 
        - ind
        - ond
    validations:
      required: true

  - type: input 
    id: package
    attributes:
      label: Package Name
      description: The name used to distinguish different runthroughs.
      placeholder: "round-1"
    validations:
      required: true
