# (C) British Crown Copyright 2026, Met Office.
# Please see LICENSE.md for license details.

# NOTE: This workflow is triggered only when issues labelled "request_file_request" are opened/editted and relies on the
# inputs given by '.github/ISSUE_TEMPLATE/generate_request_file.yml'

name: "Generate a request file"
on: 
  issues:
    types: [opened, edited]

jobs:
  process-metadata:
    if: contains(github.event.issue.labels.*.name, 'request_file_request')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - uses: actions/checkout@v3
        
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: install dependencies
        run: |
          pip install "metomi-isodatetime==1!3.0.0"
          pip install "requests==2.34.2"
        
      - name: create request file
        id: create-file
        env:
          ISSUE_BODY: |
              ${{ github.event.issue.body }}
          # pipe preseves newline properties for multilines
        run: python scripts/generate_request.py
        continue-on-error: true

      - name: return issues to user
        id: check-issues
        if: steps.create-file.outcome == 'failure'
        run: |
          gh issue comment "$NUMBER" --body "$BODY"
          echo "NOTE: Script failure has occured since no configuration file exists for the given model workflow ID"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            ${{ steps.create-file.outputs.err_msg }}.

            If you believe this to be an error, please contact a member of the CDDS team.

      - name: commit and push
        if: steps.create-file.outcome == 'success'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          git add *.cfg
          git commit -m "New request file added"
          git push origin main

          gh issue comment "$NUMBER" --body "$BODY"
          gh issue close --repo "$REPO" "$ISSUE"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            A request file has been created for you as [${{ steps.create-file.outputs.request_filename }}](https://github.com/UKNCSP/CDDS-simulation-metadata/tree/main/requests/${{ steps.create-file.outputs.request_filename }}).
            Along side this, you will need to download a copy of the associated variable list file [${{ steps.create-file.outputs.var_list }}](https://github.com/UKNCSP/CDDS-simulation-metadata/tree/main/${{ steps.create-file.outputs.var_list }}).

            You will need to make changes to the variable list file path in your local copy of the request before it can be used.
            Please be sure to read the README.md in the requests directory for guidence on setting up your request file.




      
